version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/pokotyan/study-slack
jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-cache-v1-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-cache-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - setup_remote_docker
      - run: docker build -t study-slack .
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
workflows:
  build_and_lint:
    jobs:
      - build
      - lint
